const MTN_SME = [
  {
    id: 101,
    dataplan_id: "101",
    plan_network: "MTN",
    plan_type: "SME",
    month_validate: "30 days SME",
    plan: "500.0MB",
    my_price: "145",
    resellerPrice: "135",
    apiPrice: "135",
  },
  {
    id: 102,
    dataplan_id: "102",
    plan_network: "MTN",
    plan_type: "SME",
    month_validate: "30 days SME",
    plan: "1GB",
    my_price: "225",
    resellerPrice: "215",
    apiPrice: "215",
  },
  {
    id: 103,
    dataplan_id: "103",
    plan_network: "MTN",
    plan_type: "SME",
    month_validate: "30 days SME",
    plan: "2GB",
    my_price: "450",
    resellerPrice: "430",
    apiPrice: "430",
  },
  {
    id: 104,
    dataplan_id: "104",
    plan_network: "MTN",
    plan_type: "SME",
    month_validate: "30 days SME",
    plan: "3GB",
    my_price: "675",
    resellerPrice: "645",
    apiPrice: "645",
  },

  {
    id: 105,
    dataplan_id: "105",
    plan_network: "MTN",
    plan_type: "SME",
    month_validate: "30 days SME",
    plan: "5GB",
    my_price: "1125",
    resellerPrice: "1075",
    apiPrice: "1075",
  },
  {
    id: 106,
    dataplan_id: "106",
    plan_network: "MTN",
    plan_type: "CG",
    month_validate: "30 days CG",
    plan: "500.0MB",
    my_price: "150",
    resellerPrice: "140",
    apiPrice: "140",
  },
  {
    id: 107,
    dataplan_id: "107",
    plan_network: "MTN",
    plan_type: "CG",
    month_validate: "30 days CG",
    plan: "1GB",
    my_price: "250",
    resellerPrice: "245",
    apiPrice: "245",
  },
  {
    id: 108,
    dataplan_id: "108",
    plan_network: "MTN",
    plan_type: "CG",
    month_validate: "30 days CG",
    plan: "2GB",
    my_price: "500",
    resellerPrice: "490",
    apiPrice: "490",
  },
  {
    id: 109,
    dataplan_id: "109",
    plan_network: "MTN",
    plan_type: "CG",
    month_validate: "30 days CG",
    plan: "3GB",
    my_price: "750",
    resellerPrice: "735",
    apiPrice: "735",
  },

  {
    id: 110,
    dataplan_id: "110",
    plan_network: "MTN",
    plan_type: "CG",
    month_validate: "30 days CG",
    plan: "5GB",
    my_price: "1250",
    resellerPrice: "1225",
    apiPrice: "1225",
  },
  {
    id: 111,
    dataplan_id: "111",
    plan_network: "MTN",
    plan_type: "CG",
    month_validate: "30 days CG",
    plan: "10GB",
    my_price: "2500",
    resellerPrice: "2450",
    apiPrice: "2450",
  },
  {
    id: 112,
    dataplan_id: "112",
    plan_network: "MTN",
    plan_type: "COUPON",
    month_validate: "7 days COUPON",
    plan: "750MB",
    my_price: "5000",
    resellerPrice: "50005000",
    apiPrice: "3000",
    volumeRatio: 0.75,
  },
  {
    id: 113,
    dataplan_id: "113",
    plan_network: "MTN",
    plan_type: "COUPON",
    month_validate: "7 days COUPON",
    plan: "1GB",
    my_price: "5000",
    resellerPrice: "5000",
    apiPrice: "3000",
    volumeRatio: 1,
  },
  {
    id: 114,
    dataplan_id: "114",
    plan_network: "MTN",
    plan_type: "COUPON",
    month_validate: "30 days COUPON",
    plan: "3GB",
    my_price: "5000",
    resellerPrice: "5000",
    apiPrice: "3000",
    volumeRatio: 3,
  },
];
const GLO = [
  {
    id: 201,
    dataplan_id: "201",
    network: 2,
    plan_type: "CG",
    plan_network: "GLO",
    month_validate: "30days",
    plan: "500MB",
    my_price: "5000",
    resellerPrice: "5000",
    apiPrice: "5000",
  },
  {
    id: 202,
    dataplan_id: "202",
    network: 2,
    plan_type: "CG",
    plan_network: "GLO",
    month_validate: "30days",
    plan: "1GB",
    my_price: "5000",
    resellerPrice: "5000",
    apiPrice: "5000",
  },
  {
    id: 203,
    dataplan_id: "203",
    network: 2,
    plan_type: "CG",
    plan_network: "GLO",
    month_validate: "30days",
    plan: "2GB",
    my_price: "5000",
    resellerPrice: "5000",
    apiPrice: "5000",
  },
  {
    id: 204,
    dataplan_id: "204",
    network: 2,
    plan_type: "CG",
    plan_network: "GLO",
    month_validate: "30days",
    plan: "3GB",
    my_price: "5000",
    resellerPrice: "5000",
    apiPrice: "5000",
  },
  {
    id: 205,
    dataplan_id: "205",
    network: 2,
    plan_type: "CG",
    plan_network: "GLO",
    month_validate: "30days",
    plan: "5GB",
    my_price: "5000",
    resellerPrice: "5000",
    apiPrice: "5000",
  },
  {
    id: 206,
    dataplan_id: "206",
    network: 2,
    plan_type: "CG",
    plan_network: "GLO",
    month_validate: "30days",
    plan: "10GB",
    my_price: "5000",
    resellerPrice: "5000",
    apiPrice: "5000",
  },
];
const AIRTEL = [
  {
    id: 303,
    dataplan_id: "303",
    network: 3,
    plan_type: "CG",
    plan_network: "AIRTEL",
    month_validate: "30 days",
    plan: "500MB",
    plan_amount: "5000",
    my_price: "5000",
    resellerPrice: "5000",
    apiPrice: "5000",
  },
  {
    id: 305,
    dataplan_id: "305",
    network: 3,
    plan_type: "CG",
    plan_network: "AIRTEL",
    month_validate: "30 days",
    plan: "2GB",
    plan_amount: "460",
    my_price: "460",
    resellerPrice: "440",
    apiPrice: "440",
  },
  {
    id: 306,
    dataplan_id: "306",
    network: 3,
    plan_type: "CG",
    plan_network: "AIRTEL",
    month_validate: "30 days",
    plan: "5GB",
    plan_amount: "1150",
    my_price: "1150",
    resellerPrice: "1100",
    apiPrice: "1100",
  },
  {
    id: 301,
    dataplan_id: "301",
    network: 3,
    plan_type: "CG",
    plan_network: "AIRTEL",
    month_validate: "30 days",
    plan: "100MB",
    plan_amount: "3000",
    my_price: "3000",
    resellerPrice: "3000",
    apiPrice: "3000",
  },
  {
    id: 302,
    dataplan_id: "302",
    network: 3,
    plan_type: "CG",
    plan_network: "AIRTEL",
    month_validate: "30 days",
    plan: "300MB",
    plan_amount: "3000",
    my_price: "3000",
    resellerPrice: "3000",
    apiPrice: "3000",
  },
  {
    id: 307,
    dataplan_id: "307",
    network: 3,
    plan_type: "CG",
    plan_network: "AIRTEL",
    month_validate: "30 days",
    plan: "10GB",
    plan_amount: "3000",
    my_price: "3000",
    resellerPrice: "3000",
    apiPrice: "3000",
  },
  {
    id: 308,
    dataplan_id: "308",
    network: 3,
    plan_type: "CG",
    plan_network: "AIRTEL",
    month_validate: "30 days",
    plan: "15GB",
    plan_amount: "5000",
    my_price: "5000",
    resellerPrice: "5000",
    apiPrice: "5000",
  },
  {
    id: 309,
    dataplan_id: "309",
    network: 3,
    plan_type: "CG",
    plan_network: "AIRTEL",
    month_validate: "30 days",
    plan: "20GB",
    plan_amount: "5000",
    my_price: "5000",
    resellerPrice: "5000",
    apiPrice: "5000",
  },
];

const NMOBILE = [
  {
    id: 401,
    dataplan_id: "401",
    network: 6,
    plan_type: "SME",
    plan_network: "9MOBILE",
    month_validate: "30 days",
    plan: "1GB",
    plan_amount: "350",
    my_price: "350",
    resellerPrice: "340",
    apiPrice: "340",
  },
  {
    id: 402,
    dataplan_id: "402",
    network: 6,
    plan_type: "SME",
    plan_network: "9MOBILE",
    month_validate: "30 days",
    plan: "1.5GB",
    plan_amount: "525",
    my_price: "525",
    resellerPrice: "510",
    apiPrice: "510",
  },
  {
    id: 403,
    dataplan_id: "403",
    network: 6,
    plan_type: "SME",
    plan_network: "9MOBILE",
    month_validate: "30 days",
    plan: "2GB",
    plan_amount: "700",
    my_price: "700",
    resellerPrice: "680",
    apiPrice: "680",
  },
  {
    id: 404,
    dataplan_id: "404",
    network: 6,
    plan_type: "SME",
    plan_network: "9MOBILE",
    month_validate: "30 days",
    plan: "3GB",
    plan_amount: "1050",
    my_price: "1020",
    resellerPrice: "1020",
    apiPrice: "1020",
  },
  {
    id: 405,
    dataplan_id: "405",
    network: 6,
    plan_type: "SME",
    plan_network: "9MOBILE",
    month_validate: "30 days",
    plan: "5GB",
    plan_amount: "1750",
    my_price: "1750",
    resellerPrice: "1700",
    apiPrice: "1700",
  },
  {
    id: 406,
    dataplan_id: "406",
    network: 6,
    plan_type: "SME",
    plan_network: "9MOBILE",
    month_validate: "30 days",
    plan: "10GB",
    plan_amount: "3500",
    my_price: "3500",
    resellerPrice: "3400",
    apiPrice: "3400",
  },
];

const GOTV = [
  {
    id: 17,
    cableplan_id: "17",
    cable: "GOTV",
    package: "GOtv Smallie-monthly 800",
    plan_amount: "796",
  },
  {
    id: 16,
    cableplan_id: "16",
    cable: "GOTV",
    package: "GOtv Jinja",
    plan_amount: "1640",
  },
  {
    id: 35,
    cableplan_id: "35",
    cable: "GOTV",
    package: "GOtv Smallie - Quarterly",
    plan_amount: "2100",
  },
  {
    id: 47,
    cableplan_id: "47",
    cable: "GOTV",
    package: "Gotv-jolli",
    plan_amount: "2460",
  },
  {
    id: 2,
    cableplan_id: "2",
    cable: "GOTV",
    package: "GOtv Max",
    plan_amount: "3600",
  },
  {
    id: 36,
    cableplan_id: "36",
    cable: "GOTV",
    package: "GOtv Smallie - Yearly",
    plan_amount: "6200",
  },
];

const SERVICES = [
  { serviceId: "1", serviceName: "Mtn airtime", serviceStatus: true },
  { serviceId: "2", serviceName: "Glo airtime", serviceStatus: true },
  { serviceId: "3", serviceName: "Airtel airtime", serviceStatus: true },
  { serviceId: "4", serviceName: "9mobile airtime", serviceStatus: true },
  { serviceId: "5", serviceName: "Mtn CG", serviceStatus: true },
  { serviceId: "6", serviceName: "Mtn SME", serviceStatus: true },
  { serviceId: "7", serviceName: "Glo data", serviceStatus: true },
  { serviceId: "8", serviceName: "Airtel data", serviceStatus: true },
  { serviceId: "9", serviceName: "9mobile data", serviceStatus: true },
  { serviceId: "10", serviceName: "Electricity token", serviceStatus: true },
  { serviceId: "11", serviceName: "Cable tv", serviceStatus: true },
];
module.exports = { MTN_SME, GLO, AIRTEL, NMOBILE, SERVICES };
